"""timestamp hotfix

Revision ID: 05d418b3feaf
Revises: c8d095ea6b71
Create Date: 2021-03-29 15:40:40.941704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d418b3feaf'
down_revision = 'c8d095ea6b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
