"""Initial

Revision ID: c8d095ea6b71
Revises: 4f16c1896615
Create Date: 2021-03-29 06:54:51.904066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d095ea6b71'
down_revision = '4f16c1896615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=4), nullable=True),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.Column('assign_time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courier'))
    )
    op.create_table('courier_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], name=op.f('fk_courier_hours_courier_id_courier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courier_hours'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], name=op.f('fk_order_courier_id_courier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('average_time', sa.Integer(), nullable=True),
    sa.Column('orders_number', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], name=op.f('fk_region_courier_id_courier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region'))
    )
    op.create_table('delivery_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_delivery_hours_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_hours'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_hours')
    op.drop_table('region')
    op.drop_table('order')
    op.drop_table('courier_hours')
    op.drop_table('courier')
    # ### end Alembic commands ###
